import better_exceptions


class DataCorruptionError(Exception):
    pass
